# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    # always build pull requests
    include: ['*']

jobs:
- job: BuildProject
  displayName: Build project
  pool:
    vmImage: windows-2019 # Name: Hosted Windows 2019 with VS 2019
  steps:
  
    - checkout: self
      path: 's'
      fetchDepth: 0
    - task: CopyFiles@2
      displayName: 'Copy repo contents to artifact location'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'very-important-item.txt'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: for-deploy'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'for-deploy'
      condition: succeededOrFailed()
      
- deployment: MyRelease
  displayName: My yaml deployment
  pool:
    vmImage: windows-2019
  environment: marco
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo deployment succeeded
